import os
basedir = os.path.abspath(os.path.dirname(__file__))

SQLALCHEMY_DATABASE_URI = 'sqlite:///' + os.path.join(basedir, 'app.db')
SQLALCHEMY_MIGRATE_REPO = os.path.join(basedir, 'db_repository')

WTF_CSRF_ENABLED = True
SECRET_KEY = 'thisisasecretkey'

SUBJECTS = [('spanish1', 'Spanish 1'),
            ('spanish2', 'Spanish 2'),
            ('spanish3', 'Spanish 3'),
            ('spanish4', 'Conversational Spanish'),
            ('apspanish', 'AP Spanish'),
            ('spanishfilm', 'Spanish Film'),
            ('mandarin1', 'Mandarin 1'),
            ('mandarin2', 'Mandarin 2'),
            ('mandarin3', 'Mandarin 3'),
            ('mandarin4', 'Conversational Mandarin'),
            ('apmandarin', 'AP Mandarin'),
            ('french1', 'French 1'),
            ('french2', 'French 2'),
            ('french3', 'French 3'),
            ('apfrench', 'AP French'),
            ('japanese1', 'Japanese 1'),
            ('japanese2', 'Japanese 2'),
            ('japanese3', 'Japanese 3'),
            ('apjapanese', 'AP Japanese'),
            ('latin1', 'Latin 1'),
            ('latin2', 'Latin 2'),
            ('latin3', 'Latin 3'),
            ('aplatin', 'AP Latin'),
            ('german1', 'German 1'),
            ('german2', 'German 2'),
            ('german3', 'German 3'),
            ('italian1', 'Italian 1'),
            ('italian2', 'Italian 2'),
            ('italian3', 'Italian 3'),
            ('algebra', 'Algebra'),
            ('geometry', 'Geometry'),
            ('algebra2', 'Algebra 2 / Trigonometry'),
            ('precalculus', 'Precalculus'),
            ('apabcalculus', 'AP AB Calculus'),
            ('apbccalculus', 'AP BC Calculus'),
            ('calcapplications', 'Calculus Applications'),
            ('multi', 'Multivariate Calculus'),
            ('apstat', 'AP Statistics'),
            ('global1', 'Global History Year 1'),
            ('atglobal', 'Advanced Topics Global History'),
            ('aphumangeo', 'AP Human Geography'),
            ('apeuro', 'AP European History'),
            ('apworld', 'AP World History'),
            ('global2', 'Global History Year 2'),
            ('ushistory', 'US History'),
            ('apushistory', 'AP US History'),
            ('government', 'Government'),
            ('economics', 'Economics'),
            ('apgovernment', 'AP Government'),
            ('apmacros', 'AP Macroeconomics'),
            ('apmicro', 'AP Microeconomics'),
            ('introcs1', 'Introduction to CS 1st Semester'),
            ('introcs2', 'Introduction to CS 2nd Semester'),
            ('apcs', 'AP Computer Science'),
            ('systems', 'Systems Level Programming'),
            ('graphics', 'Graphics'),
            ('softdev', 'Software Development'),
            ('drafting', 'Technical Drawing'),
            ('musicapp', 'Music Appreciation'),
            ('artapp', 'Art Appreciation'),
            ('apmusic', 'AP Music Theory'),
            ('health', 'Health'),
            ('english', 'English'),
            ('biology', 'Regents Biology'),
            ('apbiology', 'AP Biology'),
            ('appychology', 'AP Pyschology'),
            ('chemistry', 'Regents Chemistry'),
            ('apchemistry', 'AP Chemistry'),
            ('ochemistry', 'Organic Chemistry'),
            ('physics', 'Regents Physics'),
            ('apphysicsb', 'AP Physics B'),
            ('apphysicsc', 'AP Physics C')]
